name: flutter_keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 1.0.0
author: Jason Rai <jason.c.rai@gmail.com>
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.9.0

flutter:
  plugin:
    androidPackage: com.flutter.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin
