name: flutter_keyboard_visibility_web
description: An implementation for the web platform of `flutter_keyboard_visibility'
version: 1.0.1
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPlugin
        fileName: flutter_keyboard_visibility_web.dart

dependencies:
  flutter_keyboard_visibility_platform_interface: ^1.0.1
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.9.0
  flutter_test:
    sdk: flutter