name: flutter_keyboard_visibility_web
description: An implementation for the web platform of `flutter_keyboard_visibility'
version: 2.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPlugin
        fileName: flutter_keyboard_visibility_web.dart

dependencies:
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter