name: flutter_keyboard_visibility_macos
description: An implementation for the macOS platform of `flutter_keyboard_visibility'
version: 1.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: flutter_keyboard_visibility
    platforms:
      macos:
        dartPluginClass: FlutterKeyboardVisibilityPluginMacos

dependencies:
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter