name: flutter_keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 7.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

resolution: workspace

dependencies:
  meta: ^1.18.0
  flutter_keyboard_visibility_platform_interface: ^3.0.0
  flutter_keyboard_visibility_linux: ^2.0.0
  flutter_keyboard_visibility_macos: ^2.0.0
  flutter_keyboard_visibility_web: ^3.0.0
  flutter_keyboard_visibility_windows: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.14.1
  flutter_lints: ^6.0.0
  mockito: ^5.6.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jrai.flutter_keyboard_visibility
        pluginClass: FlutterKeyboardVisibilityPlugin
      ios:
        pluginClass: FlutterKeyboardVisibilityPlugin
      web:
        default_package: flutter_keyboard_visibility_web
      macos:
        default_package: flutter_keyboard_visibility_macos
      linux:
        default_package: flutter_keyboard_visibility_linux
      windows:
        default_package: flutter_keyboard_visibility_windows
