name: example_old
description: An old Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_keyboard_visibility:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: 1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true