name: example_old
description: An old Flutter application.

version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_keyboard_visibility:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: 1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true