name: flutter_keyboard_visibility_platform_interface
description: A common platform interface for the flutter_keyboard_visibility plugin.
version: 0.1.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  pedantic: 1.9.0
  flutter_test:
    sdk: flutter