name: flutter_keyboard_visibility_platform_interface
description: A common platform interface for the flutter_keyboard_visibility plugin.
version: 1.0.1
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.0.0 <2.0.0"
  plugin_platform_interface: 1.1.0-nullsafety.1

dev_dependencies:
  pedantic: 1.10.0-nullsafety.3
  flutter_test:
    sdk: flutter